title: Leo's Dev Blog
tagline: 데이터 분석가로 성장하는 블로그
description: 데이터 분석 여정을 기록합니다.
url: "https://leo-tiger-yoon.github.io"
baseurl: ""

lang: en
timezone: Asia/Seoul

theme_mode:

paginate: 10

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/

collections:
  tabs:
    output: true
    sort_by: order
